# Generated by Django 3.0.3 on 2021-12-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor', models.EmailField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('county', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Bungalow', 'Bungalow'), ('Studio', 'Studio'), ('Townhouse', 'Townhouse'), ('Maisonette', 'Maisonette')], default='Apartment', max_length=50)),
                ('sale_type', models.CharField(choices=[('For Rent', 'Rent'), ('For Sale', 'Buy')], default='For Sale', max_length=10)),
                ('main_photo', models.ImageField(upload_to='houses/')),
                ('photo_2', models.ImageField(upload_to='houses/')),
                ('photo_3', models.ImageField(upload_to='houses/')),
                ('photo_4', models.ImageField(upload_to='houses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
